

services:
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "9002:9092"
    environment:
      KAFKA_BROKERCONNECT: kafka:9092
    networks:
        - internal
    volumes:
      - ~/kui/config.yml:/etc/kafkaui/dynamic_config.yaml
networks:
  internal:
    driver: bridge
